protocol: "tcp"
regions: {
    addresses: "10.0.1.36",
    addresses: "10.0.1.56",
    addresses: "10.0.1.28",
    addresses: "10.0.1.141",
    addresses: "10.0.1.26",
    addresses: "10.0.1.93",
    addresses: "10.0.1.68",
    addresses: "10.0.1.171",
    addresses: "10.0.1.223",
    addresses: "10.0.1.8",
    addresses: "10.0.1.64",
    addresses: "10.0.1.144",
    addresses: "10.0.1.35",
    addresses: "10.0.1.250",
    addresses: "10.0.1.204",
    addresses: "10.0.1.159",
    addresses: "10.0.1.149",
    addresses: "10.0.1.55",
    addresses: "10.0.1.214",
    addresses: "10.0.1.251",
    addresses: "10.0.1.78",
    addresses: "10.0.1.92",
    addresses: "10.0.1.202",
    addresses: "10.0.1.164",
    addresses: "10.0.1.100",
    addresses: "10.0.1.4",
    addresses: "10.0.1.42",
    addresses: "10.0.1.186",
    addresses: "10.0.1.183",
    addresses: "10.0.1.203",
    addresses: "10.0.1.103",
    addresses: "10.0.1.197",
    public_addresses: "3.101.79.29",
    public_addresses: "52.53.201.95",
    public_addresses: "54.241.45.86",
    public_addresses: "13.57.238.105",
    public_addresses: "54.176.75.84",
    public_addresses: "54.241.86.39",
    public_addresses: "3.101.33.177",
    public_addresses: "18.144.71.3",
    public_addresses: "54.241.87.104",
    public_addresses: "54.193.100.14",
    public_addresses: "54.177.239.68",
    public_addresses: "54.183.151.121",
    public_addresses: "52.53.127.224",
    public_addresses: "54.176.92.6",
    public_addresses: "54.176.66.49",
    public_addresses: "184.169.210.62",
    public_addresses: "18.144.64.177",
    public_addresses: "50.18.95.10",
    public_addresses: "3.101.123.71",
    public_addresses: "184.72.14.179",
    public_addresses: "54.219.173.236",
    public_addresses: "18.144.40.128",
    public_addresses: "3.101.56.171",
    public_addresses: "13.57.26.63",
    public_addresses: "13.56.164.84",
    public_addresses: "54.176.172.120",
    public_addresses: "54.151.8.51",
    public_addresses: "13.56.183.244",
    public_addresses: "54.183.203.141",
    public_addresses: "54.153.105.79",
    public_addresses: "52.53.124.156",
    public_addresses: "13.57.185.236",
    client_addresses: "54.67.30.183",
    client_addresses: "54.176.20.92",
    client_addresses: "3.101.34.10",
    client_addresses: "54.183.40.168",
    client_addresses: "54.219.144.86",
    client_addresses: "50.18.231.140",
    client_addresses: "52.53.173.207",
    client_addresses: "3.101.109.106",
    num_replicas: 8
}

broker_ports: 2020
server_port: 2021
forwarder_port: 2022
sequencer_port: 2023

simple_partitioning {
    num_records: 100000000
    record_size_bytes: 100
}

bypass_mh_orderer: true
fs_latency_interval: 200
avg_latency_window_size: 10
synchronized_batching: true
timestamp_buffer_us: 2000
num_log_managers: 1
ddr_interval: 100
num_partitions: 4
num_workers: 3

forwarder_batch_duration: 1
sequencer_batch_duration: 5
sequencer_batch_size: 100
replication_factor: 1

# TCP buffer setting (for large latency deployments)
broker_rcvbuf: 10485760
long_sender_sndbuf: 10485760
