protocol: "tcp"
regions: {
    addresses: "10.0.1.14",
    addresses: "10.0.1.6",
    addresses: "10.0.1.189",
    addresses: "10.0.1.137",
    public_addresses: "54.219.26.217",
    public_addresses: "3.101.88.206",
    public_addresses: "13.56.138.198",
    public_addresses: "54.219.58.146",
    client_addresses: "18.144.50.166",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.240",
    addresses: "10.0.1.190",
    addresses: "10.0.1.33",
    addresses: "10.0.1.62",
    public_addresses: "54.219.101.131",
    public_addresses: "54.151.26.8",
    public_addresses: "54.177.148.143",
    public_addresses: "54.219.33.0",
    client_addresses: "54.183.73.194",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.142",
    addresses: "10.0.1.80",
    addresses: "10.0.1.116",
    addresses: "10.0.1.178",
    public_addresses: "54.177.178.35",
    public_addresses: "54.177.246.73",
    public_addresses: "54.241.120.83",
    public_addresses: "13.57.241.58",
    client_addresses: "52.53.244.50",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.197",
    addresses: "10.0.1.64",
    addresses: "10.0.1.173",
    addresses: "10.0.1.124",
    public_addresses: "13.56.12.234",
    public_addresses: "13.56.114.7",
    public_addresses: "54.193.178.152",
    public_addresses: "204.236.173.119",
    client_addresses: "52.53.233.80",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.111",
    addresses: "10.0.1.233",
    addresses: "10.0.1.175",
    addresses: "10.0.1.41",
    public_addresses: "54.193.169.7",
    public_addresses: "52.53.184.90",
    public_addresses: "54.219.217.198",
    public_addresses: "13.56.58.38",
    client_addresses: "3.101.123.13",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.16",
    addresses: "10.0.1.150",
    addresses: "10.0.1.120",
    addresses: "10.0.1.154",
    public_addresses: "54.215.122.251",
    public_addresses: "54.183.155.152",
    public_addresses: "54.219.144.255",
    public_addresses: "54.241.57.216",
    client_addresses: "54.183.203.39",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.119",
    addresses: "10.0.1.109",
    addresses: "10.0.1.87",
    addresses: "10.0.1.59",
    public_addresses: "3.101.118.110",
    public_addresses: "54.176.171.45",
    public_addresses: "18.144.73.141",
    public_addresses: "13.56.223.97",
    client_addresses: "18.144.68.27",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.45",
    addresses: "10.0.1.187",
    addresses: "10.0.1.11",
    addresses: "10.0.1.169",
    public_addresses: "54.183.232.83",
    public_addresses: "52.53.129.31",
    public_addresses: "204.236.171.66",
    public_addresses: "52.53.203.97",
    client_addresses: "52.53.191.206",
    num_replicas: 1,
}

broker_ports: 2020
server_port: 2021
forwarder_port: 2022
sequencer_port: 2023

simple_partitioning {
    num_records: 100000000
    record_size_bytes: 100
}

mh_orderer_batch_duration: 5
forwarder_batch_duration: 1
sequencer_batch_duration: 5
sequencer_batch_size: 100
sequencer_rrr: true
replication_factor: 1

# Forwarder
bypass_mh_orderer: false

# Scheduler
num_workers: 3

num_log_managers: 2
num_partitions: 4

# TCP buffer setting (for large latency deployments)
broker_rcvbuf: 10485760
long_sender_sndbuf: 10485760
