regions: {
    addresses: "10.0.1.36",
    addresses: "10.0.1.56",
    addresses: "10.0.1.28",
    addresses: "10.0.1.141",
    public_addresses: "3.101.79.29",
    public_addresses: "52.53.201.95",
    public_addresses: "54.241.45.86",
    public_addresses: "13.57.238.105",
    client_addresses: "54.67.30.183",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.26",
    addresses: "10.0.1.93",
    addresses: "10.0.1.68",
    addresses: "10.0.1.171",
    public_addresses: "54.176.75.84",
    public_addresses: "54.241.86.39",
    public_addresses: "3.101.33.177",
    public_addresses: "18.144.71.3",
    client_addresses: "54.176.20.92",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.223",
    addresses: "10.0.1.8",
    addresses: "10.0.1.64",
    addresses: "10.0.1.144",
    public_addresses: "54.241.87.104",
    public_addresses: "54.193.100.14",
    public_addresses: "54.177.239.68",
    public_addresses: "54.183.151.121",
    client_addresses: "3.101.34.10",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.35",
    addresses: "10.0.1.250",
    addresses: "10.0.1.204",
    addresses: "10.0.1.159",
    public_addresses: "52.53.127.224",
    public_addresses: "54.176.92.6",
    public_addresses: "54.176.66.49",
    public_addresses: "184.169.210.62",
    client_addresses: "54.183.40.168",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.149",
    addresses: "10.0.1.55",
    addresses: "10.0.1.214",
    addresses: "10.0.1.251",
    public_addresses: "18.144.64.177",
    public_addresses: "50.18.95.10",
    public_addresses: "3.101.123.71",
    public_addresses: "184.72.14.179",
    client_addresses: "54.219.144.86",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.78",
    addresses: "10.0.1.92",
    addresses: "10.0.1.202",
    addresses: "10.0.1.164",
    public_addresses: "54.219.173.236",
    public_addresses: "18.144.40.128",
    public_addresses: "3.101.56.171",
    public_addresses: "13.57.26.63",
    client_addresses: "50.18.231.140",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.100",
    addresses: "10.0.1.4",
    addresses: "10.0.1.42",
    addresses: "10.0.1.186",
    public_addresses: "13.56.164.84",
    public_addresses: "54.176.172.120",
    public_addresses: "54.151.8.51",
    public_addresses: "13.56.183.244",
    client_addresses: "52.53.173.207",
    num_replicas: 1,
}
regions: {
    addresses: "10.0.1.183",
    addresses: "10.0.1.203",
    addresses: "10.0.1.103",
    addresses: "10.0.1.197",
    public_addresses: "54.183.203.141",
    public_addresses: "54.153.105.79",
    public_addresses: "52.53.124.156",
    public_addresses: "13.57.185.236",
    client_addresses: "3.101.109.106",
    num_replicas: 1,
}

warehouses: 1200

num_partitions: 4
